name: agora
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_svg: ^2.2.1
  google_fonts: ^6.1.0
  http: ^1.1.0
  dio: ^5.4.0
  shared_preferences: ^2.2.0
  provider: ^6.1.0
  image_picker: ^1.2.1
  file_picker: ^10.3.7
  record: ^6.1.2
  path_provider: ^2.1.5
  permission_handler: ^12.0.1
  universal_html: ^2.3.0
  url_launcher: ^6.3.2
  open_file: ^3.5.10
  audioplayers: ^6.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
  - assets/images/logo.original.svg
